### ISSUE TITLE
Missing urlparse requirement

### ISSUE THREAD

**Issue by athompson-r7** [royhodgman/cloud-formation-codegen#1]
Is `urlparse` really needed?  I get the below error running `pip install -r requirements.txt`.  I commented `urlparse` out in `requirements.txt` and was able to install.

```
Collecting urlparse (from -r requirements.txt (line 4))
  Could not find a version that satisfies the requirement urlparse (from -r requirements.txt (line 4)) (from versions: )
  Some externally hosted files were ignored as access to them may be unreliable (use --allow-external urlparse to allow).
No matching distribution found for urlparse (from -r requirements.txt (line 4))
```

**Comment by athompson-r7** [comment]
After installing, tried running the command in the readme and get the below error.  I think something is still broken.

```
~/code/cloud-formation-codegen[master*]% scrapy crawl aws-cf                           
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 7, in <module>
    from scrapy.cmdline import execute
  File "/Library/Python/2.7/site-packages/scrapy/__init__.py", line 48, in <module>
    from scrapy.spiders import Spider
  File "/Library/Python/2.7/site-packages/scrapy/spiders/__init__.py", line 10, in <module>
    from scrapy.http import Request
  File "/Library/Python/2.7/site-packages/scrapy/http/__init__.py", line 12, in <module>
    from scrapy.http.request.rpc import XmlRpcRequest
  File "/Library/Python/2.7/site-packages/scrapy/http/request/rpc.py", line 7, in <module>
    from six.moves import xmlrpc_client as xmlrpclib
ImportError: cannot import name xmlrpc_client
```

**Comment by royhodgman** [comment]
Does using virtualenv work for you?

``` bash
VIRTUAL_ENV_DIR=<PATH_TO_VIRTUAL_ENV_DIR_TO_BE_CREATED>
viralenv $VIRUAL_ENV_DIR
git clone https://github.com/royhodgman/cloud-formation-codegen.git
cd cloud-formation-codegen
source $VIRUAL_ENV_DIR/bin/activate
pip install -r requirements.txt
$VIRUAL_ENV_DIR/bin/scrapy crawl aws-cf
```

**Comment by athompson-r7** [comment]
I did try to use virtualenv.  Looking at your steps here, it might have still been using the non-virtualenv scrapy bin.

I will retest with these steps.

**Comment by royhodgman** [comment]
And if you have `PYTHONPATH` defined in your environment, that may mess things up too.

**Comment by athompson-r7** [comment]
These steps worked perfectly.

BTW, there were some typos in the steps; I opened #2 to fix them.

**Comment by royhodgman** [comment]
I'm glad they worked, thanks for fixing my typos.
